In [1]:
import numpy as np
bools= np.array([False, False, True, False])
bools.any()

True

In [2]:
bools.all()

False

In [3]:
a= np.array ([1,2,3,4])
(a>3).all()

False

In [4]:
(a>3).any()

True

In [5]:
arr=np.random.randn(100)
(arr>0).sum()

49

In [6]:
arr=np.random.randn(8)
arr

array([ 0.19067042, -1.24098067,  0.80206502, -0.36093615,  2.04733453,
        0.03380583,  1.52255597, -0.90873859])

In [7]:
np.sort(arr)

array([-1.24098067, -0.90873859, -0.36093615,  0.03380583,  0.19067042,
        0.80206502,  1.52255597,  2.04733453])

In [8]:
arr

array([ 0.19067042, -1.24098067,  0.80206502, -0.36093615,  2.04733453,
        0.03380583,  1.52255597, -0.90873859])

In [11]:
arr.sort()
arr

array([-1.24098067, -0.90873859, -0.36093615,  0.03380583,  0.19067042,
        0.80206502,  1.52255597,  2.04733453])

In [12]:
arr=np.random.randn(5,3)
arr

array([[ 0.47752373, -0.67507281, -0.37466687],
       [ 0.41575332, -0.74551919,  0.53351714],
       [ 1.38530518, -1.98909154, -1.17986777],
       [-0.3625581 ,  0.16507484,  0.43393995],
       [ 1.21411771, -1.09646868,  1.05124485]])

In [13]:
arr.sort(1)
arr

array([[-0.67507281, -0.37466687,  0.47752373],
       [-0.74551919,  0.41575332,  0.53351714],
       [-1.98909154, -1.17986777,  1.38530518],
       [-0.3625581 ,  0.16507484,  0.43393995],
       [-1.09646868,  1.05124485,  1.21411771]])

In [14]:
a=np.array([1,2,3,4])
(a>3).all()

False

In [15]:
(a>3).any()

True

In [16]:
add=lambda x,y : x+y
print(type(add))

print(add(2,3))

<class 'function'>
5


In [21]:
def multiply2 (x):
    return x*2
x= map(multiply2,[1,2,3,4,5])
x

In [19]:
print (type(x))

<class 'map'>


In [22]:
print(list(x))

[2, 4, 6, 8, 10]


In [23]:
print (x)

In [24]:
list_a = [{'name': 'python','points':10},
         {'name':'java','points':8}]
print(list_a)

[{'name': 'python', 'points': 10}, {'name': 'java', 'points': 8}]


In [25]:
list(map(lambda x: x['name'],list_a))

['python', 'java']

In [26]:
list(map(lambda x:x['points']*10,list_a))

[100, 80]

In [27]:
list(map(lambda x:x['name']=="python",list_a))

[True, False]

In [30]:
list_1= [1,2,3]
list_2 = [4,5,6]
list (map(lambda x,y:x+y,list_1,list_2))

[5, 7, 9]

In [31]:
list_a = [{'name': 'python','points':10},
         {'name':'java','points':8}]
print(list_a)

[{'name': 'python', 'points': 10}, {'name': 'java', 'points': 8}]


In [32]:
list(filter(lambda x:x['name']== 'python',list_a))

[{'name': 'python', 'points': 10}]

In [33]:
def my_gen():
    n = 1
    print('This is printed first')
    yield n 
    
    n = n+1
    print('This is printed second')
    yield n
    
    n=n+1
    print('This is printed at last')
    yield n

In [34]:
a=my_gen()
next(a)

This is printed first


1

In [35]:
x = np.array ([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
y= np.array([[6,23], [-1,7],[8,9]])
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [37]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [38]:
x = np.random.randn(3,3)
x

array([[-0.2317523 ,  0.9686566 , -0.54482091],
       [-1.9840313 , -0.08438691,  0.34185214],
       [ 1.30064799, -1.28332831, -1.44773966]])

In [39]:
np.linalg.inv(x)

array([[-0.14276722, -0.53493193, -0.0725856 ],
       [ 0.61795968, -0.26577679, -0.29531118],
       [-0.67604354, -0.24498828, -0.49416835]])

In [40]:
x.dot(np.linalg.inv(x))

array([[ 1.00000000e+00,  8.38274099e-17,  7.70506816e-18],
       [-1.21456855e-17,  1.00000000e+00, -3.43247298e-18],
       [ 1.16029328e-16, -2.24157309e-16,  1.00000000e+00]])

In [41]:
a = np.array([[0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30]])
print('first array:')
print(a)

first array:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [47]:
b = np.array([[1,2,3],
              [1,10,1],
             [10,11,12],
             [12,22,22]])
print('second array:')
print(b)

second array:
[[ 1  2  3]
 [ 1 10  1]
 [10 11 12]
 [12 22 22]]


In [48]:
print('first array + second array')
print(a + b)

first array + second array
[[ 1  2  3]
 [11 20 11]
 [30 31 32]
 [42 52 52]]
